spring:
  application:
    name: razorpay
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/razorpayDB}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

vault:
  service:
    master-key: HelloRazorpayProject

payment:
  simulator:
    poll-interval-ms: 500000000
    chaos-mode: NORMAL
    methods:
      UPI:
        min-delay-seconds: 1
        max-delay-seconds: 3
        success-rate: 90
      NETBANKING:
        min-delay-seconds: 4
        max-delay-seconds: 10
        success-rate: 90
      CARD:
        min-delay-seconds: 2
        max-delay-seconds: 4
        success-rate: 90


jwt:
  secret-key: hiuhuihihiujiabcdefgkjnjnhijlmnopqrstuvwxyz109
